/** @type {import('tailwindcss').Config} */
const config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        oat: {
          50: "#FEFCFA",
          100: "#F9F5F1",
          200: "#F5EFEB",
          300: "#E8DCD2",
          400: "#D6C6BA",
          500: "#BBA89B",
          600: "#998477",
          700: "#77665C",
          800: "#51453F",
          900: "#2F2925",
          950: "#1D1815",
        },
        primary: {
          50: "#F7F4FA",
          100: "#ECE5F1",
          200: "#D8CBE2",
          300: "#BFAACE",
          400: "#9F82B3",
          500: "#806194",
          600: "#6C5B7B",
          700: "#574861",
          800: "#3F3548",
          900: "#2B2632",
          950: "#1B1720",
          DEFAULT: "var(--color-primary)",
          foreground: "var(--color-primary-foreground)",
          hover: "var(--color-primary-hover)",
          active: "var(--color-primary-active)",
          disabled: "var(--color-primary-disabled)",
        },
        secondary: {
          50: "#F7FBEF",
          100: "#EEF7D8",
          200: "#DDF0B2",
          300: "#C4E57A",
          400: "#ACD957",
          500: "#98CB3C",
          600: "#78A729",
          700: "#5D8023",
          800: "#4B6621",
          900: "#3F5620",
          950: "#20300F",
          DEFAULT: "var(--color-secondary)",
          foreground: "var(--color-secondary-foreground)",
          hover: "var(--color-secondary-hover)",
          active: "var(--color-secondary-active)",
          disabled: "var(--color-secondary-disabled)",
        },
        accent: {
          50: "#FFF6ED",
          100: "#FFE8D1",
          200: "#FFD1A8",
          300: "#FFB26F",
          400: "#FF8D3D",
          500: "#F3722C",
          600: "#DB571E",
          700: "#B64018",
          800: "#91351B",
          900: "#752F1C",
          950: "#3F150A",
          DEFAULT: "var(--color-accent)",
          foreground: "var(--color-accent-foreground)",
          hover: "var(--color-accent-hover)",
          active: "var(--color-accent-active)",
          disabled: "var(--color-accent-disabled)",
        },
        surface: {
          DEFAULT: "var(--color-surface)",
          muted: "var(--color-surface-muted)",
          elevated: "var(--color-surface-elevated)",
          sunken: "var(--color-surface-sunken)",
        },
        card: {
          DEFAULT: "var(--color-card)",
          foreground: "var(--color-card-foreground)",
        },
        muted: {
          DEFAULT: "var(--color-muted)",
          foreground: "var(--color-muted-foreground)",
        },
        disabled: {
          DEFAULT: "var(--color-disabled)",
          foreground: "var(--color-disabled-foreground)",
        },
        border: "var(--color-border)",
        input: "var(--color-input)",
        ring: "var(--color-ring)",
        background: "var(--color-background)",
        foreground: "var(--color-foreground)",
        success: {
          DEFAULT: "var(--color-success)",
          foreground: "var(--color-success-foreground)",
          surface: "var(--color-success-surface)",
          border: "var(--color-success-border)",
        },
        warning: {
          DEFAULT: "var(--color-warning)",
          foreground: "var(--color-warning-foreground)",
          surface: "var(--color-warning-surface)",
          border: "var(--color-warning-border)",
        },
        error: {
          DEFAULT: "var(--color-error)",
          foreground: "var(--color-error-foreground)",
          surface: "var(--color-error-surface)",
          border: "var(--color-error-border)",
        },
        info: {
          DEFAULT: "var(--color-info)",
          foreground: "var(--color-info-foreground)",
          surface: "var(--color-info-surface)",
          border: "var(--color-info-border)",
        },
      },
      borderRadius: {
        card: "var(--radius-card)",
        control: "var(--radius-control)",
      },
      boxShadow: {
        soft: "var(--shadow-soft)",
        focus: "var(--shadow-focus)",
      },
    },
  },
  plugins: [],
};

module.exports = config;
